name: Build
on:
  workflow_dispatch:
    inputs:
      datfilter:
        description: 'DAT Filter'
        default: ''
        required: false
        type: string
jobs:
  build:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Pages
        uses: actions/configure-pages@main
      - name: Setup Perl
        uses: perl-actions/install-with-cpanm@main
        with:
          install: |
            Archive::Zip
            LWP::UserAgent
            LWP::Protocol::https
      - name: build
        run: perl build.pl ${{ github.event.inputs.datfilter }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@main
        with:
          path: 'out'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
